apiVersion: v1
items:
- apiVersion: v1
  data:
    appsettings.json: |
      {
        "ConnectionStrings": {
          "SqlConnection": "Server=host.containers.internal;Database=model;User Id=sa; Password=replaceme;"
        },
        "WelcomeMessage": "I'am using a mounted appsetting.json",
        "Logging": {
          "LogLevel": {
            "Default": "Information",
            "Microsoft.AspNetCore": "Warning"
          }
        },
        "AllowedHosts": "*"
      }
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"appsettings.json":"{\n  \"ConnectionStrings\": {\n    \"SqlConnection\": \"Server=host.containers.internal;Database=model;User Id=sa; Password=replaceme;\"\n  },\n  \"WelcomeMessage\": \"I'am using a mounted appsetting.json\",\n  \"Logging\": {\n    \"LogLevel\": {\n      \"Default\": \"Information\",\n      \"Microsoft.AspNetCore\": \"Warning\"\n    }\n  },\n  \"AllowedHosts\": \"*\"\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"app-config","namespace":"default"}}
    name: app-config
    namespace: default
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"simple-dotnet6-startup","app.kubernetes.io/component":"simple-dotnet6-startup","app.kubernetes.io/instance":"simple-dotnet6-startup","app.kubernetes.io/name":"simple-dotnet6-startup","app.kubernetes.io/part-of":"simple-dotnet6-startup","app.openshift.io/runtime-version":"latest"},"name":"simple-dotnet6-startup","namespace":"default"},"spec":{"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"7111-tcp","port":7111,"protocol":"TCP","targetPort":7111}],"selector":{"app":"simple-dotnet6-startup","deploymentconfig":"simple-dotnet6-startup"},"sessionAffinity":"None","type":"ClusterIP"}}
    labels:
      app: simple-dotnet6-startup
      app.kubernetes.io/component: simple-dotnet6-startup
      app.kubernetes.io/instance: simple-dotnet6-startup
      app.kubernetes.io/name: simple-dotnet6-startup
      app.kubernetes.io/part-of: simple-dotnet6-startup
      app.openshift.io/runtime-version: latest
    name: simple-dotnet6-startup
    namespace: default
  spec:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 7111-tcp
      port: 7111
      protocol: TCP
      targetPort: 7111
    selector:
      app: simple-dotnet6-startup
      deploymentconfig: simple-dotnet6-startup
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"simple-dotnet6-startup","app.kubernetes.io/component":"simple-dotnet6-startup","app.kubernetes.io/instance":"simple-dotnet6-startup","app.kubernetes.io/name":"simple-dotnet6-startup","app.kubernetes.io/part-of":"simple-dotnet6-startup","app.openshift.io/runtime":"dotnet","app.openshift.io/runtime-namespace":"simple-dotnet6-app"},"name":"simple-dotnet6-startup","namespace":"default"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"simple-dotnet6-startup"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"simple-dotnet6-startup","deploymentconfig":"simple-dotnet6-startup"}},"spec":{"containers":[{"image":"quay.io/fmeneses/simple-dotnet6-startup:latest","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":"http"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"simple-dotnet6-startup","ports":[{"containerPort":7111,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":"http"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"cpu":"300m","memory":"512Mi"},"requests":{"cpu":"300m","memory":"256Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"runAsNonRoot":true,"seccompProfile":{"type":"RuntimeDefault"}},"startupProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":"http"},"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":2},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/app/appsettings.json","name":"app-config","subPath":"appsettings.json"}]}],"restartPolicy":"Always","volumes":[{"configMap":{"defaultMode":420,"name":"app-config"},"name":"app-config"}]}}}}
    labels:
      app: simple-dotnet6-startup
      app.kubernetes.io/component: simple-dotnet6-startup
      app.kubernetes.io/instance: simple-dotnet6-startup
      app.kubernetes.io/name: simple-dotnet6-startup
      app.kubernetes.io/part-of: simple-dotnet6-startup
      app.openshift.io/runtime: dotnet
      app.openshift.io/runtime-namespace: simple-dotnet6-app
    name: simple-dotnet6-startup
    namespace: default
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: simple-dotnet6-startup
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: simple-dotnet6-startup
          deploymentconfig: simple-dotnet6-startup
      spec:
        containers:
        - image: quay.io/fmeneses/simple-dotnet6-startup:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: simple-dotnet6-startup
          ports:
          - containerPort: 7111
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /app/appsettings.json
            name: app-config
            subPath: appsettings.json
        restartPolicy: Always
        volumes:
        - configMap:
            defaultMode: 420
            name: app-config
          name: app-config
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app":"simple-dotnet6-startup","app.kubernetes.io/component":"simple-dotnet6-startup","app.kubernetes.io/name":"simple-dotnet6-startup","app.kubernetes.io/part-of":"simple-dotnet6-startup","app.openshift.io/runtime":"dotnet"},"name":"release-name-simple-dotnet6-startup","namespace":"default"},"spec":{"maxReplicas":5,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":80,"type":"Utilization"}},"type":"Resource"},{"resource":{"name":"memory","target":{"averageUtilization":80,"type":"Utilization"}},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"release-name-simple-dotnet6-startup"}}}
    labels:
      app: simple-dotnet6-startup
      app.kubernetes.io/component: simple-dotnet6-startup
      app.kubernetes.io/name: simple-dotnet6-startup
      app.kubernetes.io/part-of: simple-dotnet6-startup
      app.openshift.io/runtime: dotnet
    name: release-name-simple-dotnet6-startup
    namespace: default
  spec:
    maxReplicas: 5
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: release-name-simple-dotnet6-startup
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"route.openshift.io/v1","kind":"Route","metadata":{"annotations":{},"labels":{"app":"simple-dotnet6-startup","app.kubernetes.io/component":"simple-dotnet6-startup","app.kubernetes.io/instance":"simple-dotnet6-startup","app.kubernetes.io/name":"simple-dotnet6-startup","app.kubernetes.io/part-of":"simple-dotnet6-startup","app.openshift.io/runtime-version":"latest"},"name":"simple-dotnet6-startup","namespace":"default"},"spec":{"port":{"targetPort":"7111-tcp"},"tls":{"insecureEdgeTerminationPolicy":"Redirect","termination":"edge"},"to":{"kind":"Service","name":"simple-dotnet6-startup","weight":100},"wildcardPolicy":"None"}}
    labels:
      app: simple-dotnet6-startup
      app.kubernetes.io/component: simple-dotnet6-startup
      app.kubernetes.io/instance: simple-dotnet6-startup
      app.kubernetes.io/name: simple-dotnet6-startup
      app.kubernetes.io/part-of: simple-dotnet6-startup
      app.openshift.io/runtime-version: latest
    name: simple-dotnet6-startup
    namespace: default
  spec:
    port:
      targetPort: 7111-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: simple-dotnet6-startup
      weight: 100
    wildcardPolicy: None
kind: List
metadata: {}
