apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-dotnet6-startup.fullname" . }}
  labels:
    {{- include "simple-dotnet6-startup.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ipFamilies: {{ toYaml .Values.service.ipFamilies | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    {{- include "simple-dotnet6-startup.selectorLabels" . | nindent 4 }}
